[config]

[config.wallpaper]
set     = true
command = "awww img --transition-type wave --transition-angle 270 --transition-fps 60 {{ image }}"

[templates.quickshell]
input_path  = 'templates/quickshell.json'
output_path = '~/.local/state/quickshell/generated/colors.json'

[templates.neovim]
input_path  = "templates/nvim-colors.json"
output_path = "~/.config/matugen/themes/nvim-colors.json"
post_hook   = "pkill -SIGUSR1 nvim"

[templates.ghostty]
input_path  = 'templates/ghostty'
output_path = '~/.config/ghostty/themes/Matugen'
post_hook   = 'pkill -SIGUSR2 ghostty'
